#是否使用json读取参数
isFile: true

#基础配置
clientBaseConfig:
  admin: 10001
  robot: 10002
  wakeUpWord: Hi Alice
  standbyWord: Nothing,thanks
  promptUpWord: Hi master,what i to do?
  robotName: Alice
  standbyPrompt: You welcome
  loadingWord: 正在检索...
  isPublic: false
  isConcurrency: false

#线程池配置
executor:
  corePoolSize: 5
  maxPoolSize: 20
  workQueue: 25

# chatGPT配置
chatGPT:
  email:
  password:
  sessionToken: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..AJ-U2ZtU2PoYfMYS.2EYElccx6sRcGg5dgMwApVDyu3WhjsPAxJnUSeJPNDE-ukpGQBvYJCnOYVCFQQYRk5025Ydk58A5NzVa6O3zFBo3uPhArbXhTlOSei-nt06zmsKlnnFdSLOjO6zC_P6qHsB4Eo5Qnxq2Vb6f3gBMMSA7V2OY7wm-f3_iaDew38PCjctN_UZ1EZOsJ1TfAvtcgeEFslY_KCCL01Iva4tA-iKzsqW5X9ViN08hkPfVJeGt-7skYVuD8kIh6Fxt9K__2qeqlvU7WdDb1j8eRQlhTCLQYQyP98elOqRpw2vLP3Kl1hBS0YBfEKz3kLwu9PkIsish-Y6-HHqghi2Wsp1-KsnF6ouLdvTLePhR2mzvnOOwgHATl6wui1HsvygA01l2mKZyQcwd2NOwMJJSdOtpvazZuBiCZo-qB4DuJ7ciEZ8xg-6ATe9Kit5wweKZX0Dc8BpO1hgjfQQhdoklgHxHRgaoLiC5cNXiYM02jrZ6VOfKN5HmjtvGEqf5KkVL1CSTnJdrl8Hm-lpqPDi2-sg8xUyMSrso97Z31y78OJ_V1AVe3ETwTGriRAshmonnnHP7fAS4kA5i4oSG2MjgyyLkpTmEhGh_rpvmzzwvrzQcGT7Vp-4ZhCZG6-meKO7RAuhK4WPhCtJDfx9Erw6x5gJx5FaZL0buByF1SHWoX0u4V3i9uQOvlMn0E9BULLUkHH0dJc2SU9__CQZLVN_ONndTjETCyQ8DnuZmeeiuLSxNQ4iHRefqw2AL2Vpm5To2EaV0-WU_4HTdAAnC7RgGjJPGY-XX0634gwIcMNvmBItdf9oEWPNYIbmTHGfgIIuYqj5fnwG3rv8L0yz0JUSz9qy7sROiXookfTgbr6l6A7NoM9gvosPU_KmKPw3gjycV41DVzPKAb7brYLPfm7ci0zYonywikd5v49HB7kYqvhIiBcAkdC-xL5ijkaTQWbNqoYCAlK3uaV7RjU6kEEq84h_ru72ljl7Rn0Oda1pSqngoILHsdasOeAsj3pyZ9g6gY8EJihaCfLUdau1FH02coSWZJlbjH4vsQAONJYze6tp8sJShzTmA6DWpEQ4wqab-6hJDn9338NzPTGyp3NccciSCWxblKGH4gdpLsTai_wBPH1k_ngjrUhGNmA0q33Sle99jojpeNzlO4UrBpwWDxQY7L4123mqFEaaxdgIvh5LddBO47X7_68q8NbO507V4cucSJZHx1TQ3YsS-E3yIf3O9RGIFqrmU3Upqxm_23W5LSq5U64FGla8UWRAtALLsgCqtJWfWACtdD7rm2kz27ZeVWViBJMll3qW5pvmoSR0Jy1rQI0c2DDhibfkARSxISrjZUo00kQdXHFn4GTrwF4dIUiX2v4-V8sAvNZvJ_PE89l2q17oZBYMZmwl9UiTsWb1mrQxoKi7rO3C3O6KLyE1rwYOaqTVP7yqWY3kEaaByMIoI4Yd5JWQZ4NdD12OjOOShNQQr1ws-tLXIgo3zNcEi_qaHQjqdcF7FuIXs_A7HhyiTjcjii4pDDjR7CfAHNNn_UqZ-tswe4tZ-UkM6bNQFVZiENiBZ6wkTL7s24VYVqlOWIzy3HGMXRfJKpcVN-z2yJHHNKogOA7hZmZVSnK2kB9vRjGpSTHSMSoskw3Ip0EAgZ9s0eYyce52DpSA4gghctsRKTD_NarZojnch5SrgyjVZ6ob1G0q3HzNxsgDbWTnetFmumvHKf85bKGQomiYvQxu4Jp7S384NOMVzXY5k_8hN9-gWT9iApVbZOeaxUPRzZPgzjLrP7suTJENAq1OwJjE-JfrDEDZnlofAL_il97d5FRfWAMYsiWcPvinlWZ-Q51CHNCq9fzlE90QuT1DxMLhUeVvRS3BhnMPktgKdXGs7sKX94vBArDXsjcFwTFK9vXKkb-zm9npdTmbmKyVpSoDMK2r_pNabQX2k4xrm_jSsv9JZTVA1IOsN8sgGd3wFqDh0Z4bNIhRtZGr56LniOJdD1ASzewHch2kEe5W_LuxuMGDWWfqjlayezvupn78r_IrSukeAUuUZMtJ0EIKIw5E_6iDXZ408gH2OFKGCqgASpHJjWLYDNnMlw5gz1TDIw2VuaMOREJPURUwGoGFVtcGBLZP4ddDI3m8gjtnVCjAYzDmk9D3Jswb_40qW1q5uO9hAtb0LVUs9vGIe7OyvImHIoE7hXYUXH8ChG_KPTA2uX5HROFvQSIc9rpQLegjrT2RRIVcKncyrOaeSutb2tK7q0io5eB393zPAJXeEfZGxExCwvb0s4DjO9CymT4EiIeky0q-ZNttKNop-GJoRb6U82hdFidxb-ZTDlnXSfyTHw2OJJttZSg.Pz8QhsEnHurFwTxIvjBXZQ

server:
  port: 8080
